# SPDX-FileCopyrightText: 2022-present toybox.py Contributors
#
# SPDX-License-Identifier: MIT

[AnimatedSprite]
url = "https://github.com/Whitebrim/AnimatedSprite"
description = "Sprite class extension with imagetable animation and finite state machine support for Playdate."
author = "Whitebrim <deni7off@yandex.ru>"
license = "MIT"

[Aspen]
url = "https://github.com/DidierMalenfant/Aspen"
description = "A Simple Platformer ENgine for the Playdate."
author = "Didier Malenfant <coding@malenfant.net>"
license = "MIT"

[LDtkImporter]
url = "https://github.com/NicMagnier/PlaydateLDtkImporter"
description = "Load tilemaps created with LDtk in your playdate games."
author = "Nic Magnier"

[librif]
url = "https://github.com/risolvipro/librif"
description = "A lightweight library to encode and read grayscale images."
author = "Risolvi Productions <https://github.com/risolvipro>"
license = "MIT"

[modplayer]
url = "https://github.com/DidierMalenfant/modplayer"
description = "Amiga SoundTracker/ProTracker Module Player for Playdate."
author = "Didier Malenfant <coding@malenfant.net>"
license = "MIT"

[pdbase]
url = "https://github.com/DidierMalenfant/pdbase"
description = "Handy utility functions and SDK additions."
author = "Didier Malenfant <coding@malenfant.net>"
license = "MIT"

[playbox2d]
url = "https://github.com/DidierMalenfant/playbox2d"
description = "A port of box2d lite from Erin Catto (http://www.gphysics.com)."
author = "Dustin Mierau <https://github.com/mierau>"
license = "MIT"

[Plupdate]
url = "https://github.com/DidierMalenfant/Plupdate"
description = "The playdate.update() manager."
author = "Didier Malenfant <coding@malenfant.net>"
license = "MIT"

[RobkohrFont]
url = "https://github.com/RobKohr/robkohr-mono-5x8-font-for-playdate"
description = "A 5x8 font that is readable & monospaced without it looking too boring."
author = "Rob Kohr <spam@robkohr.com>"

[Sequence]
url = "https://github.com/NicMagnier/PlaydateSequence"
description = "Create animations with simple sequences of easing functions in your playdate game."
author = "Nic Magnier"

[Signal]
url = "https://github.com/DidierMalenfant/Signal.git"
description = "A Lua class for subscribing to keys and notifying subscribers of that key."
author = "Dustin Mierau <https://github.com/mierau>"

[TileMap]
url = "https://github.com/DidierMalenfant/TileMap"
description = "A drop-in replacement for 'playdate.graphics.tilemap' with new features."
author = "Didier Malenfant <coding@malenfant.net>"
license = "MIT"

[TiledUp]
url = "https://github.com/DidierMalenfant/TiledUp"
description = "A Playdate toybox which lets you import and use Tiled levels."
author = "Didier Malenfant <coding@malenfant.net>"
license = "MIT"
